apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoveileder
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  prometheus:
    enabled: true
    path: /prometheus
  redis:
    - instance: cache
      access: readwrite
  ingresses:
    - "https://syfoveileder.intern.nav.no"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
        - application: syfomoteoversikt
        - application: syfooversikt
        - application: syfooversiktsrv
    outbound:
      external:
        - host: "graph.microsoft.com"
        - host: "axsys.prod-fss-pub.nais.io"
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  env:
    - name: GRAPHAPI_URL
      value: "https://graph.microsoft.com"
    - name: AXSYS_CLIENT_ID
      value: "prod-fss.org.axsys"
    - name: AXSYS_URL
      value: "https://axsys.prod-fss-pub.nais.io"
