apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoveileder
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfoveileder/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfoveileder/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfoveileder/internal/prometheus
  ingresses:
    - "https://syfoveileder.nais.adeo.no"
  vault:
    enabled: true
  env:
    - name: APP_NAME
      value: "syfoveileder"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: NO_NAV_SECURITY_OIDC_ISSUER_VEILEDER_DISCOVERYURL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_OIDC_ISSUER_VEILEDER_ACCEPTEDAUDIENCE
      value: 9b4e07a3-4f4c-4bab-b866-87f62dff480d
    - name: AXSYS_URL
      value: https://axsys.nais.adeo.no/api
    - name: GRAPHAPI_URL
      value: https://graph.microsoft.com
    # Miljøvariabler som hentes fra vault:
    # AAD_SYFOVEILEDER_CLIENTID_USERNAME
    # AAD_SYFOVEILEDER_CLIENTID_PASSWORD
