apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoveileder
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /is_alive
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfoveileder.dev.intern.nav.no"
    - "https://syfoveileder.nais.preprod.local"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  webproxy: true
  env:
    - name: GRAPHAPI_URL
      value: https://graph.microsoft.com
    - name: AXSYS_URL
      value: https://axsys.nais.preprod.local/api
