apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoveileder
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfoveileder/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfoveileder/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfoveileder/internal/prometheus
  ingresses:
    - "https://syfoveileder.dev.intern.nav.no"
    - "https://syfoveileder.nais.preprod.local"
  vault:
    enabled: true
  env:
    - name: APP_NAME
      value: "syfoveileder"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDERAAD_DISCOVERYURL
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration"
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDERAAD_ACCEPTEDAUDIENCE
      value: "bdde0d4f-4ced-4aa0-9168-9cfe9044ac10"
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_DISCOVERYURL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_JWT_ISSUER_VEILEDER_ACCEPTEDAUDIENCE
      value: 38e07d31-659d-4595-939a-f18dce3446c5
    - name: AXSYS_URL
      value: https://axsys.nais.preprod.local/api
    - name: GRAPHAPI_URL
      value: https://graph.microsoft.com
    # Miljøvariabler som hentes fra vault:
    # AAD_SYFOVEILEDER_CLIENTID_USERNAME
    # AAD_SYFOVEILEDER_CLIENTID_PASSWORD
