apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoveileder
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfoveileder/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfoveileder/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /syfoveileder/internal/prometheus
  ingresses:
    - "https://syfoveileder.intern.nav.no"
    - "https://syfoveileder.nais.adeo.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: prod-fss
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
  env:
    - name: APP_NAME
      value: "syfoveileder"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: GRAPHAPI_URL
      value: https://graph.microsoft.com
    - name: AXSYS_URL
      value: https://axsys.nais.adeo.no/api
