no.nav.security.jwt:
  issuer:
    veilederaad:
      discoveryurl: ${azure.app.well.known.url}
      accepted_audience: ${azure.app.client.id},${syfoveileder.client.id.deprecated}
      cookiename: ID_token

aad.syfoveileder.clientid:
  username: <SETTES FRA NAISERATOR>
  password: <SETTES FRA NAISERATOR>

logging.config: 'classpath:logback-spring.xml'

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: '/internal'
    exposure.include: 'prometheus'
    path-mapping.prometheus: '/prometheus'
  endpoint:
    flyway:
      enabled: false
  health:
    db:
      enabled: false

server:
  servlet:
    context-path: /syfoveileder

spring:
  main.banner-mode: 'off'


