logging.config: 'classpath:logback-spring.xml'

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: '/internal'
    exposure.include: 'prometheus'
    path-mapping.prometheus: '/prometheus'

server:
  servlet:
    context-path: /syfoprediksjoner

spring:
  main.banner-mode: 'off'
  jta.atomikos.datasource:
          max-pool-size: 32
          min-pool-size: 8

