no.nav.security.oidc:
  issuers: veileder
  issuer:
    veileder:
      discoveryurl: <SETTES FRA FASIT>
      accepted_audience: <SETTES FRA FASIT>
      cookie_name: isso-idtoken

aad_syfoveileder_clientid:
  username: <SETTES FRA FASIT>
  password: <SETTES FRA FASIT>

logging.config: 'classpath:logback-spring.xml'

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: '/internal'
    exposure.include: 'prometheus'
    path-mapping.prometheus: '/prometheus'
  endpoint:
    flyway:
      enabled: false
  health:
    db:
      enabled: false

server:
  servlet:
    context-path: /syfoveileder

spring:
  main.banner-mode: 'off'
  jta.atomikos.datasource:
          max-pool-size: 32
          min-pool-size: 8
  flyway:
    enabled: false

