name: Deploy to dev-gcp

on:
  workflow_dispatch:
    inputs:
      gitCommit:
        description: "Git ref to deploy (the complete hash):"
        required: true
        default: ""

jobs:
  deploy-dev:
    name: Deploy to NAIS Dev-gcp
    permissions:
      contents: read
      id-token: write
    uses: navikt/isworkflows/.github/workflows/manual-deploy-dev.yml@master
    with:
      git-commit: ${{ github.event.inputs.gitCommit }}
    secrets: inherit
